#!/bin/bash

cyc=`grep "engine.duration" /home/gto500/hubu/workspace/PeerNetProtocolsAnca/configurations/poldercast-net.cfg | cut -d'*' -f2`
cyc=$(( $cyc - 6 ))
echo $cyc

tpc=`grep "^\TICKS_PER_CYCLE" /home/gto500/hubu/workspace/PeerNetProtocolsAnca/configurations/poldercast-net.cfg | cut -d' ' -f3`

echo $tpc

javac Main.java
java Main $cyc $tpc fb_1ksample.txt workspace/PeerNetProtocolsAnca/results/logs/*.txt 
